name: 'Reviewer Check'
description: 'Checks for more than one Codeowner reviewer on a PR.'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true
  min_reviewers:
    description: 'Minimum number of codeowner reviews'
    required: true
  ignore_teams:
    description: 'Ignore team codeowners, i.e., only consider individual codeowners'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
