name: 'Reviewer Check'
description: 'Checks for more than one Codeowner reviewer on a PR.'

inputs:
  TOKEN:
    description: 'GitHub Token or Personal Access Token - must use PAT when include_teams is set to `true`.'
    required: true
  min_reviewers:
    description: 'Minimum number of codeowner reviews.'
    required: true
  include_teams:
    description: 'Set to `true` to include team codeowners; when include_teams is set to `false` or NOT set, team codeowners will be ignored.'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
