name: 'Reviewer Check'
description: 'Checks for more than one Codeowner reviewer on a PR.'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true

runs:
  using: 'node16'
  main: 'index.js'
